# Generated by Django 4.2.3 on 2023-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('left_index_finger_data', models.TextField(blank=True, null=True)),
                ('right_index_finger_data', models.TextField(blank=True, null=True)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('programme', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='student_pictures/')),
            ],
        ),
    ]
